name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build binary
      run: go build -o klo
    
    - name: Test CLI
      run: |
        ./klo examples/hello.klo
        ./klo examples/calculator.klo
    
    - name: Test transpilation
      run: |
        ./klo --transpile --output test.go examples/hello.klo
        go run test.go

  build-matrix:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        if [ "$GOOS" = "windows" ]; then
          go build -o klo-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        else
          go build -o klo-${{ matrix.goos }}-${{ matrix.goarch }}
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: klo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: klo-*
